version: '2'
services:
  web:
    image: 'mariodavid/kubanische-kaninchenzuechterei:latest'
    ports:
     - "8082:8080"
  db:
    image: "blacklabelops/hsqldb:latest"
    environment:
      - HSQLDB_USER=kaninchen
      - HSQLDB_PASSWORD=kaninchen
      - HSQLDB_DATABASE_ALIAS=kaninchen
